import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashCursor from "@/components/cursor";
import NavBar from "@/components/ui/custom/Nav";
import { ThemeProvider } from "@/components/ui/custom/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
         attribute={'class'}
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
        >
        <SplashCursor/>
        <NavBar />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
